spring:
  application:
    name: zuul
  rabbitmq:
    host: 192.168.32.132
    port: 5672
    username: admin
    password: admin
    
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

zuul:
  routes:
    item-service: /item-service/**
    user-service: /user-service/**
    order-service: /order-service/** 
  retryable: true  #手动启动重试
  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
            
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream